import { SolMethod, SolScope } from '@metamask/keyring-api';

import type { SolanaKeyringAccount } from '../../services/keyring/Keyring';

/**
 * Solana account scopes.
 */
export const ALL_SCOPES = [SolScope.Mainnet, SolScope.Testnet, SolScope.Devnet];

/**
 * Mock Solana Keyring Accounts as they would actually be generated by the Solana Keyring when using seed phrase:
 *
 * sugar interest animal afford dog imitate relief lizard width strategy embark midnight
 */

export const MOCK_SOLANA_KEYRING_ACCOUNT_0: SolanaKeyringAccount = {
  address: 'BLw3RweJmfbTapJRgnPRvd962YDjFYAnVGd1p5hmZ5tP',
  index: 0,
  type: 'solana:data-account',
  id: '123e4567-e89b-12d3-a456-426614174000',
  options: {
    imported: false,
  },
  methods: [SolMethod.SendAndConfirmTransaction],
  scopes: ALL_SCOPES,
};

export const MOCK_SOLANA_KEYRING_ACCOUNT_0_PRIVATE_KEY_BYTES = Uint8Array.from([
  201, 78, 195, 68, 173, 217, 17, 236, 239, 65, 202, 20, 18, 250, 160, 56, 151,
  150, 31, 187, 150, 2, 50, 207, 153, 155, 163, 236, 59, 134, 83, 102,
]);

export const MOCK_SOLANA_KEYRING_ACCOUNT_1: SolanaKeyringAccount = {
  address: 'FvS1p2dQnhWNrHyuVpJRU5mkYRkSTrubXHs4XrAn3PGo',
  index: 1,
  type: 'solana:data-account',
  id: '123e4567-e89b-12d3-a456-426614174001',
  options: {
    imported: false,
  },
  methods: [SolMethod.SendAndConfirmTransaction],
  scopes: ALL_SCOPES,
};

export const MOCK_SOLANA_KEYRING_ACCOUNT_1_PRIVATE_KEY_BYTES = Uint8Array.from([
  58, 174, 98, 154, 253, 237, 125, 206, 109, 159, 134, 239, 189, 179, 106, 243,
  179, 3, 131, 173, 86, 94, 23, 72, 63, 239, 110, 125, 30, 210, 84, 194,
]);

export const MOCK_SOLANA_KEYRING_ACCOUNT_2: SolanaKeyringAccount = {
  address: '27h6cm6S9ag5y4ASi1a1vbTSKEsQMjEdfvZ6atPjmbuD',
  index: 2,
  type: 'solana:data-account',
  id: '123e4567-e89b-12d3-a456-426614174002',
  options: {
    imported: false,
  },
  methods: [SolMethod.SendAndConfirmTransaction],
  scopes: ALL_SCOPES,
};

export const MOCK_SOLANA_KEYRING_ACCOUNT_2_PRIVATE_KEY_BYTES = Uint8Array.from([
  217, 83, 246, 6, 62, 72, 189, 87, 62, 43, 66, 168, 205, 49, 195, 7, 119, 128,
  101, 85, 226, 215, 67, 23, 223, 247, 240, 157, 111, 214, 41, 42,
]);

export const MOCK_SOLANA_KEYRING_ACCOUNT_3: SolanaKeyringAccount = {
  address: '3SYHDFbhoxuTCYCGRw7KSL8GbwUoByjtvyy7pUZeAhh8',
  index: 3,
  type: 'solana:data-account',
  id: '123e4567-e89b-12d3-a456-426614174003',
  options: {
    imported: false,
  },
  methods: [SolMethod.SendAndConfirmTransaction],
  scopes: ALL_SCOPES,
};

export const MOCK_SOLANA_KEYRING_ACCOUNT_3_PRIVATE_KEY_BYTES = Uint8Array.from([
  197, 249, 13, 144, 108, 95, 220, 46, 159, 169, 72, 221, 192, 106, 72, 127, 10,
  3, 95, 186, 173, 83, 212, 239, 180, 41, 7, 213, 92, 250, 122, 122,
]);

export const MOCK_SOLANA_KEYRING_ACCOUNT_4: SolanaKeyringAccount = {
  address: 'FDUGdV6bjhvw5gbirXCvqbTSWK9999kcrZcrHoCQzXJK',
  index: 4,
  type: 'solana:data-account',
  id: '123e4567-e89b-12d3-a456-426614174004',
  options: {
    imported: false,
  },
  methods: [SolMethod.SendAndConfirmTransaction],
  scopes: ALL_SCOPES,
};

export const MOCK_SOLANA_KEYRING_ACCOUNT_4_PRIVATE_KEY_BYTES = Uint8Array.from([
  182, 222, 182, 183, 103, 56, 65, 161, 67, 188, 55, 244, 249, 208, 7, 60, 253,
  87, 234, 231, 209, 140, 109, 175, 247, 42, 249, 9, 224, 62, 60, 54,
]);

export const MOCK_SOLANA_KEYRING_ACCOUNT_5: SolanaKeyringAccount = {
  address: 'GN1DST49kafBmRDnKKwUbR6nJWoqzSJBPoHwcTXzgmkH',
  index: 5,
  type: 'solana:data-account',
  id: '123e4567-e89b-12d3-a456-426614174005',
  options: {
    imported: false,
  },
  methods: [SolMethod.SendAndConfirmTransaction],
  scopes: ALL_SCOPES,
};

export const MOCK_SOLANA_KEYRING_ACCOUNT_5_PRIVATE_KEY_BYTES = Uint8Array.from([
  130, 137, 152, 17, 6, 45, 56, 235, 140, 148, 107, 75, 184, 175, 54, 227, 184,
  27, 142, 254, 188, 4, 157, 96, 132, 101, 35, 165, 225, 205, 245, 102,
]);

export const MOCK_SOLANA_KEYRING_ACCOUNTS = [
  MOCK_SOLANA_KEYRING_ACCOUNT_0,
  MOCK_SOLANA_KEYRING_ACCOUNT_1,
  MOCK_SOLANA_KEYRING_ACCOUNT_2,
  MOCK_SOLANA_KEYRING_ACCOUNT_3,
  MOCK_SOLANA_KEYRING_ACCOUNT_4,
  MOCK_SOLANA_KEYRING_ACCOUNT_5,
] as const;

export const MOCK_SOLANA_KEYRING_ACCOUNTS_PRIVATE_KEY_BYTES = {
  [MOCK_SOLANA_KEYRING_ACCOUNT_0.id]:
    MOCK_SOLANA_KEYRING_ACCOUNT_0_PRIVATE_KEY_BYTES,
  [MOCK_SOLANA_KEYRING_ACCOUNT_1.id]:
    MOCK_SOLANA_KEYRING_ACCOUNT_1_PRIVATE_KEY_BYTES,
  [MOCK_SOLANA_KEYRING_ACCOUNT_2.id]:
    MOCK_SOLANA_KEYRING_ACCOUNT_2_PRIVATE_KEY_BYTES,
  [MOCK_SOLANA_KEYRING_ACCOUNT_3.id]:
    MOCK_SOLANA_KEYRING_ACCOUNT_3_PRIVATE_KEY_BYTES,
  [MOCK_SOLANA_KEYRING_ACCOUNT_4.id]:
    MOCK_SOLANA_KEYRING_ACCOUNT_4_PRIVATE_KEY_BYTES,
  [MOCK_SOLANA_KEYRING_ACCOUNT_5.id]:
    MOCK_SOLANA_KEYRING_ACCOUNT_5_PRIVATE_KEY_BYTES,
} as const;
